language: python
python:
  - "3.5.2"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls  # To install python-coveralls
  - pip install coverage       # To install coverage.py

# command for running testss
script:
  - py.test 
#command for getting the test coverage
after_success:
  - coveralls # upload reports to coveralls.io